name: seek
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  sqflite: ^2.3.2
  get_it: ^7.6.7
  path_provider: ^2.1.3
  mockito: ^5.0.16
  uuid: ^3.0.4
  build_runner: ^2.1.7
  equatable:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: IndieFlower
  #     fonts:
  #       - asset: fonts/IndieFlower-Regular.ttf
